config/routes.rb
Rails.application.routes.draw do
	root 'welcome#index'
	get 'welcome/index'

  get '/login' , to: 'login#login'
  post '/login' , to: 'login#login'
  get '/login/logout'#, to: 'login#logout'
	
	resources :parents
	
	resources :grades
	
	resources :students
    
  resources :teachers
  
	resources :divisions
    
  resources :offerings
    
  resources :members

	get '/student' , to: 'welcome#student'
	get '/parent' , to: 'welcome#parent'
	get '/teacher' , to: 'welcome#teacher'
	get '/admin' , to: 'welcome#admin'
    
    get '/password/:id' , to: 'members#password'
    post '/password' , to: 'members#password'
    
  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/student.rb
class Student < ActiveRecord::Base
    has_one :member, dependent: :destroy, validate: true
    belongs_to :parent
    
	validates :first_name, presence: true
	validates :last_name, presence: true
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_filter :authorize, :except =>  [:index]
  def new
    @student = Student.new
    @student.member = Member.new
  end
  
  def create
    @student = Student.new(student_params)
    @student.build_member(member_params) 
    if @student.save && @student.member.errors.none?
      redirect_to @student
    else
      render 'new'
    end
  end
  
  def update
    @student = Student.find(params[:id])
    if @student.member.nil?
      @student.build_member(member_params) 
    end
    if @student.update(student_params) && @student.member.errors.none?
      redirect_to @student
    else
      render 'edit'
    end
  end
  
  def show
    @student = Student.find(params[:id])
  end
  
  def index
    @students = Student.all
  end
  
  def edit
    @student = Student.find(params[:id])
  end
  
  def destroy
    @student = Student.find(params[:id])
    @student.destroy
    
    redirect_to students_path
  end
  
  private
  def student_params
    params.require(:student).permit(:first_name, :last_name, :title, :aka)
  end
  def member_params
    params.require(:member).permit(:name, :password, :password_confirmation)
  end
  def member_name_param
    params.require(:member).permit(:name)
  end
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/students/_form.html.erb
<%= form_for @student do |f| %>

 <% if @student.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@student.errors.count, "error") %> prohibited
        this student from being saved:
      </h2>
      <ul>
        <% @student.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <% if @student.member.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@student.member.errors.count, "error") %> prohibited
        this student from being saved:
      </h2>
      <ul>
        <% @student.member.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :first_name, "First Name" %><br>
    <%= f.text_field :first_name %>
  </p>
 
  <p>
    <%= f.label :last_name, "Last Name" %><br>
    <%= f.text_field :last_name %>
  </p>
  <h2> Login Info </h2>
 <%= fields_for :member, @student.member do |m| %>
  <p>
    <%= m.label :name %>
    <%= m.text_field :name, :size => 40 %>
  </p>
  
  <p>
    <%= m.label :password %>
    <%= m.password_field :password, :size => 40 %>
  </p>
  
  <p>
    <%= m.label :password_confirmation, "Confirmation" %>
    <%= m.password_field :password_confirmation, :size => 40 %>
  </p>
<% end %>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/students/edit.html.erb
<%= content_for :page_title, "Renert Choice Friday"%>
<div>
<h1>Editing Students</h1>
 
<%= render 'form' %>
 
<%= link_to 'Back', students_path %>
</div>

app/views/students/index.html.erb
<h1>Listing of Students</h1>
 
<%= link_to 'New Student', new_student_path %> 
 
<table>
  <tr>
    <th>First Name</th>
    <th>Last Name</th>
  </tr>
 
  <% @students.each do |student| %>
    <tr>
      <td><%= student.first_name %></td>
      <td><%= student.last_name %></td>
      <td><%= link_to 'Show', student_path(student) %></td>
      <td><%= link_to 'Edit', edit_student_path(student) %></td>
      <td><%= link_to 'Delete', student_path(student),
              method: :delete,
              data: { confirm: 'Are you sure you want to delete the student?' } %></td>
    </tr>
    </tr>
  <% end %>
</table>



<%= link_to 'Welcome Page', root_path %>
</div>

app/views/students/new.html.erb
<%= content_for :page_title, "Renert Choice Friday"%>
<div>
<h1>Creating a Student</h1>

<%= render 'form' %>

<%= link_to 'Back', students_path %>
</div>

app/views/students/show.html.erb
<div>
<p>
  <strong>First Name:</strong>
  <%= @student.first_name %>
</p>
 
<p>
  <strong>LastName:</strong>
  <%= @student.last_name %>
</p>
<%= link_to 'New Student', new_student_path %>
<%= link_to 'Edit', edit_student_path %>
<%= link_to 'Back', students_path %>
</div>