config/routes.rb
Rails.application.routes.draw do
	root 'welcome#index'
	get 'welcome/index'

  get '/login' , to: 'login#login'
  post '/login' , to: 'login#login'
  get '/login/logout'#, to: 'login#logout'
	
	resources :parents
	
	resources :grades
	
	resources :students
    
  resources :teachers
  
	resources :divisions
    
  resources :offerings
    
  resources :members

	get '/student' , to: 'welcome#student'
	get '/parent' , to: 'welcome#parent'
	get '/teacher' , to: 'welcome#teacher'
	get '/admin' , to: 'welcome#admin'
    
    get '/password/:id' , to: 'members#password'
    post '/password' , to: 'members#password'
    
  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/division.rb
class Division < ActiveRecord::Base
  has_and_belongs_to_many :offerings
  has_many :grades

	validates :div_number, presence: true,
		length: { maximum: 1 }, inclusion: {in: %w(K 1 2 3 4)}
end

app/controllers/divisions_controller.rb
class DivisionsController < ApplicationController
  before_filter :authorize, :except =>  [:index]
	def index
		@divisions = Division.all		
	end
	
	def show
		@division = Division.find(params[:id])
	end

	def new
		@division = Division.new
	end

	def edit
		@division = Division.find(params[:id])
	end
	
	def create
		@division = Division.new(division_params)
        @division.grade_ids = params[:division][:grade_ids]
		
		if @division.save
			redirect_to @division
		else
			render 'new'
		end

	end

	def update
		@division = Division.find(params[:id])
        @division.grade_ids = params[:division][:grade_ids]
        
        if @division.update(division_params)
            redirect_to @division
        else
            render 'edit'
        end
    end

  def destroy
    @division = Division.find(params[:id])
    @division.destroy
 
    redirect_to divisions_path
  end
private
	def division_params
		params.require(:division).permit(:div_number)
	end
end

app/views/divisions/_form.html.erb
<%= form_for @division do |f| %>

<% if @division.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@division.errors.count, "error") %> prohibited
        this division from being saved:
      </h2>
      <ul>
        <% @division.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  
  <p>
    <%= f.label :division %><br>
    <%= f.text_field :div_number %>
  </p>
  
  <p>
	<%= f.label :Grade_ids, "grades" %><br> <%= f.collection_select(:grade_ids, Grade.all.order(:id), :id, :grade_level, {:prompt => "select one or more"}, {:multiple => true}) %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/divisions/_grade.html.erb
<%= grade.grade_level %> 

app/views/divisions/edit.html.erb
<div>
<h1>Editing Division</h1>
<%= render 'form' %>
<%= link_to 'Back', divisions_path %>
</div>

app/views/divisions/index.html.erb
<h1>Listing of Divisions </h1>
<%= link_to 'New Division', new_division_path %> 
 
<table>
  <tr>
    <th>Division</th>    
    <th>Grades</th>
    <th>&nbsp;</th>
  </tr>
 
  <% @divisions.each do |division| %>
    <tr>
      <td><%= division.div_number %></td>
      <td><%= render partial: "grade", collection: division.grades %></td>
      <td><%= link_to 'Show', division_path(division) %></td>
      <td><%= link_to 'Edit', edit_division_path(division) %></td>
      <td><%= link_to 'Delete', division_path(division),
              method: :delete,
              data: { confirm: 'Are you sure you want to delete the division?' } %></td>
    </tr>
    </tr>
  <% end %>
</table>


<%= link_to 'Welcome Page', root_path %>

app/views/divisions/new.html.erb
<div>
<h1> Create a Division</h1>
<%= render 'form' %>
<%= link_to 'back', controller: 'divisions' %>
<%= link_to 'Welcome Page', root_path %>
</div>

app/views/divisions/show.html.erb
<p>
  <strong>Division:</strong>
  <%= @division.div_number %>
</p>

<p>
  <strong>Grades:</strong>
  <td><%= render partial: "grade", collection: @division.grades %></td>
</p>

 
<%= link_to 'New Division', new_division_path %>
<%= link_to 'Edit', edit_division_path %>
<%= link_to 'back', controller: 'divisions' %>
<%= link_to 'Welcome Page', root_path %>