config/routes.rb
Rails.application.routes.draw do
	root 'welcome#index'
	get 'welcome/index'

  get '/login' , to: 'login#login'
  post '/login' , to: 'login#login'
  get '/login/logout'#, to: 'login#logout'
	
	resources :parents
	
	resources :grades
	
	resources :students
    
  resources :teachers
  
	resources :divisions
    
  resources :offerings
    
  resources :members

	get '/student' , to: 'welcome#student'
	get '/parent' , to: 'welcome#parent'
	get '/teacher' , to: 'welcome#teacher'
	get '/admin' , to: 'welcome#admin'
    
    get '/password/:id' , to: 'members#password'
    post '/password' , to: 'members#password'
    
  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/teacher.rb
class Teacher < ActiveRecord::Base
  has_and_belongs_to_many :offerings
  has_one :member, dependent: :destroy, validate: true

  validates :firstname, presence: true
  validates :lastname, presence: true
  validates :title, length: {maximum: 6}
  validates :aka, uniqueness: true

end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
  before_filter :authorize, :except =>  [:index]
  def new
    @teacher = Teacher.new
    @teacher.member = Member.new
  end
  
  def create
    @teacher = Teacher.new(teacher_params)
    @teacher.build_member(member_params) 
    if @teacher.save && @teacher.member.errors.none?
      redirect_to @teacher
    else
      render 'new'
    end
  end
  
  def update
    @teacher = Teacher.find(params[:id])
    if @teacher.member.nil?
      @teacher.build_member(member_params) 
    end
    if @teacher.update(teacher_params) && @teacher.member.errors.none?
      redirect_to @teacher
    else
      render 'edit'
    end
  end
  
  def show
    @teacher = Teacher.find(params[:id])
  end
  
  def index
    @teachers = Teacher.all
  end
  
  def edit
    @teacher = Teacher.find(params[:id])
  end
  
  def destroy
    @teacher = Teacher.find(params[:id])
    @teacher.destroy
    
    redirect_to teachers_path
  end
  
  private
  def teacher_params
    params.require(:teacher).permit(:firstname, :lastname, :title, :aka)
  end
  def member_params
    params.require(:member).permit(:name, :password, :password_confirmation)
  end
  def member_name_param
    params.require(:member).permit(:name)
  end
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/views/teachers/_form.html.erb
<%= form_for @teacher do |f| %>
 
  <% if @teacher.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@teacher.errors.count, "error") %> prohibited
        this teacher from being saved:
      </h2>
      <ul>
        <% @teacher.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <% if @teacher.member.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@teacher.member.errors.count, "error") %> prohibited
        this teacher from being saved:
      </h2>
      <ul>
        <% @teacher.member.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= f.label :firstname , "First Name" %><br>
    <%= f.text_field :firstname %>
  </p>
 
  <p>
    <%= f.label :lastname, "LastName" %><br>
    <%= f.text_field :lastname %>
  </p>
  
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
 
  <p>
    <%= f.label :aka,"AKA" %><br>
    <%= f.text_field :aka %>
  </p>
  <h2> Login Info </h2>
 <%= fields_for :member, @teacher.member do |m| %>
  <p>
    <%= m.label :name %>
    <%= m.text_field :name, :size => 40 %>
  </p>
  
  <p>
    <%= m.label :password %>
    <%= m.password_field :password, :size => 40 %>
  </p>
  
  <p>
    <%= m.label :password_confirmation, "Confirmation" %>
    <%= m.password_field :password_confirmation, :size => 40 %>
  </p>
<% end %>
 
  <p>
    <%= f.submit %>
  </p>
 
<% end %>

app/views/teachers/edit.html.erb
<h2>You are editing the Teacher.</h2>
 
<%= render 'form' %>
 
<%= link_to 'Back', teachers_path %>

app/views/teachers/index.html.erb
<h1>The list of Teachers:</h1>

<%= link_to 'New Teacher', new_teacher_path %>

<table>
  <tr>
    <th>First Name</th>
    <th>Last Name</th>
    <th>Title</th>
    <th>Aka</th>
    <th>Username</th>
  </tr>
 
  <% @teachers.each do |t| %>
    <tr>
      <td><%= t.firstname %></td>
      <td><%= t.lastname %></td>
      <td><%= t.title %></td>
      <td><%= t.aka %></td>
      <td><%= t.member.nil? ? '' : t.member.name %></td>
      <td><%= link_to 'Show', teacher_path(t) %></td>
      <td><%= link_to 'Edit', edit_teacher_path(t) %></td>
      <td><%= link_to 'Delete', teacher_path(t),
              method: :delete,
              data: { confirm: 'Are you sure you want to condemn this teacher to the eternal fires of hell?' } %></td>
    </tr>
  <% end %>
</table>

<%= link_to 'Welcome Page', root_path %>

app/views/teachers/new.html.erb
<h2>You are creating a Teacher.</h2>

<%= render 'form' %>
 
<%= link_to 'Back', teachers_path %>

app/views/teachers/show.html.erb
<p>
  <strong>First Name:</strong>
  <%= @teacher.firstname %>
</p>
 
<p>
  <strong>Last Name:</strong>
  <%= @teacher.lastname %>
</p>

<p>
  <strong>Title:</strong>
  <%= @teacher.title %>
</p>

<p>
  <strong>Aka:</strong>
  <%= @teacher.aka %>
</p>

<p>
  <strong>username:</strong>
  <%= @teacher.member.nil? ? '' : @teacher.member.name %>
</p>

<%= link_to 'Create a Teacher', new_teacher_path %>
<%= link_to 'Edit the Teacher', edit_teacher_path %>
<%= link_to 'Kill the Teacher', teacher_path(@teacher),
    method: :delete,
    data: { confirm: 'Are you sure you want to condemn this teacher to the eternal fires of hell?' } %>
  
<%= link_to 'Back', teachers_path %>