config/routes.rb
Rails.application.routes.draw do
	root 'welcome#index'
	get 'welcome/index'

  get '/login' , to: 'login#login'
  post '/login' , to: 'login#login'
  get '/login/logout'#, to: 'login#logout'
	
	resources :parents
	
	resources :grades
	
	resources :students
    
  resources :teachers
  
	resources :divisions
    
  resources :offerings
    
  resources :members

	get '/student' , to: 'welcome#student'
	get '/parent' , to: 'welcome#parent'
	get '/teacher' , to: 'welcome#teacher'
	get '/admin' , to: 'welcome#admin'
    
    get '/password/:id' , to: 'members#password'
    post '/password' , to: 'members#password'
    
  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/member.rb
require 'digest/sha1'

class Member < ActiveRecord::Base
  attr_accessor :password
  attr_accessor :password_confirmation
  belongs_to :teacher
  belongs_to :student
  belongs_to :parent
  
  validates_presence_of :name
  validates_length_of :name, :within => 2..40
  validates_uniqueness_of :name, :case_sensitive => false

  validates_presence_of :password, :if => :password_required?
  validates_presence_of :password_confirmation, :if => :password_required?
  validates_length_of :password, :within => 2..40, :if => :password_required?
  validates_confirmation_of :password, :if => :password_required?
  
  before_save :encrypt_password
  
  def self.identify(name, password)
    u = find_by_name(name)
    u && u.identified?(password) ? u : nil
  end
  
  def identified?(password)
    hashed_password == encrypt(password)
  end
  
  def self.encrypt(password, salt)
    Digest::SHA1.hexdigest("#{salt}#{password}")
  end
  
  def encrypt(password)
    self.class.encrypt(password, salt)
  end
  
  def admin?
    self.teacher_id.nil? && self.parent_id.nil? && self.student_id.nil?
  end
  
  protected
  def encrypt_password
    return if password.blank?
    self.salt = "random#{rand()}" # unique salt per user (overkill for this app)
    self.hashed_password = encrypt(password)
  end
  
  def password_required?
    hashed_password.blank? || !password.blank?
  end
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  #before_filter :authorize, :except =>  [:index, :show]
  #before_filter :authorize_edit, :only => [:edit, :update]

  # GET /members
  # GET /members.xml
  def index
    @members = Member.all().select{|m| m.admin? }

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @members }
    end
  end

  # GET /members/1
  # GET /members/1.xml
  def show
    @member = Member.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @member }
    end
  end

  # GET /members/new
  # GET /members/new.xml
  def new
    @member = Member.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @member }
    end
  end

  # GET /members/1/edit
  def edit
    @member = Member.find(params[:id])
  end
  def password
    @member = Member.find(params[:id])
  end

  # POST /members
  # POST /members.xml
  def create
    @member = Member.new(member_params)

    respond_to do |format|
      if @member.save
        format.html { redirect_to(members_url, :notice => 'Member was successfully created.') }
        format.xml  { render :xml => @member, :status => :created, :location => @member }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @member.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /members/1
  # PUT /members/1.xml
  def update
    begin  
      @member = Member.find(params[:id])
    rescue ActiveRecord::RecordNotFound
       @link = Member.new(params[:member])
      flash[:notice] = "Record not found, presumed deleted by another user, can recreate it"
      render :action => "new"
      return 
    end
    respond_to do |format|
      if @member.update_attributes(member_params)
        format.html { redirect_to(members_url, :notice => 'Member was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @member.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /members/1
  # DELETE /members/1.xml
  def destroy
    begin
      @member = Member.find(params[:id])
      @member.destroy
    rescue ActiveRecord::RecordNotFound
      flash[:notice] = "Record not found, presumed deleted by another user"
    end

    respond_to do |format|
      format.html { redirect_to(members_url) }
      format.xml  { head :ok }
    end
  end
  
  private
  def authorize_edit
    unless session[:board_member] ||  params[:id] == session[:member_id].to_s 
      if session[:member_id] 
        flash[:notice] = "Can only edit own record" 
      else
        flash[:notice] = "Login required for this action" 
      end
      redirect_to(:controller => 'members')
    end
  end
  
  private
		def member_params
			params.require(:member).permit(:name, :password, :password_confirmation)
		end

end

app/helpers/members_helper.rb
module MembersHelper
end

app/views/members/_member.html.erb
<p><%= (logged_in? && (logged_in_as(member.id))) ? link_to(h(member.name) , edit_member_path(member)) : member.name %> <span class='shy'>&nbsp; <%= (member.admin? && !logged_in_as(member.id)) ? (link_to 'Delete', member_path(member),
	method: :delete,
	data: { confirm: 'Are you sure you want to delete the member?' } ) : '' %>
</span></p>

app/views/members/edit.html.erb
<h2>Update Member</h2>
<div class="member">
<%= form_for(@member) do |f| %>
<% if @member.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@member.errors.count, "error") %> prohibited
        this member from being saved:
      </h2>
      <ul>
        <% @member.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :name, "Name" %>
    <%= f.text_field :name, :size => 40 %>
  </p>
  
  <p>Leave both password fields blank if you do not want to change the password.</p>
  
  <p>
    <%= f.label :password, "Password" %>
    <%= f.password_field :password, :size => 40 %>
  </p>
  
  <p>
    <%= f.label :password_confirmation, "Confirmation" %>
    <%= f.password_field :password_confirmation, :size => 40 %>
  </p>
  
  <p>
    <%= f.submit 'Update' %> or <%= link_to 'Cancel and go back to Members page', members_path %>
  </p>
  
<% end %>
</div>
<%= link_to 'Back', members_path %>

app/views/members/index.html.erb
<% content_for :page_title, "Members Admin Page"%>
<h2>Members allowed to edit this site</h2>
<p><%= link_to 'New Member', new_member_path %></p>
<div class="links">
<%= render @members %>
</div>

app/views/members/new.html.erb
<h2>New Member</h2>
<div class="member">
<%= form_for(@member) do |f| %>

<% if @member.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@member.errors.count, "error") %> prohibited
        this member from being saved:
      </h2>
      <ul>
        <% @member.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label "Name" %>
    <%= f.text_field :name, :size => 40 %>
  </p>
  
  <p>
    <%= f.label "Password" %>
    <%= f.password_field :password, :size => 40 %>
  </p>
  
  <p>
    <%= f.label "Confirmation" %>
    <%= f.password_field :password_confirmation, :size => 40 %>
  </p>
  
  <p>
    <%= f.submit 'Create' %> or <%= link_to 'Cancel', members_path %>
  </p>
  
<% end %>
</div>
<%= link_to 'Back', members_path %>

app/views/members/password.html.erb
<h2>Change your Password</h2>

<%= form_for(@member) do |f| %>
<% if @member.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@member.errors.count, "error") %> prohibited
        this member from being saved:
      </h2>
      <ul>
        <% @member.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  
  <p>
    <%= f.label :password, "Password" %>
    <%= f.password_field :password, :size => 40 %>
  </p>
  
  <p>
    <%= f.label :password_confirmation, "Confirmation" %>
    <%= f.password_field :password_confirmation, :size => 40 %>
  </p>
  
  <p>
    <%= f.submit 'Update' %> or <%= link_to 'Cancel and go back to Members page', members_path %>
  </p>
  
<% end %>
<%= link_to 'Back', members_path %>

app/views/members/show.html.erb
<h2>Member details</h2>
<div class="member">
<%= render @member %>

<%= link_to 'Edit', edit_member_path(@member) %> |
<%= link_to 'Back', members_path %>